### ISSUE TITLE
Loading historical messages for a topic

### ISSUE THREAD

**Issue by BadalZ** [topcoder-platform/Lauscher#1]
When user select a topic and hits view messages, it is not loading any messages currently.

1. By Default, it should fetch past 20 messages from the topic. 
2. User should be also able to select to & from date (historical date range) and should be able to fetch records (Lets keep 100 msg max in order to prevent browser crashing due to excessive data)

Apart from this, Switching between topic should work seamlessly (as it will load past 20 records).

CC: @cwdcwd

**Comment by BadalZ** [comment]
@callmekatootie : Have we merged latest fixes in dev & master branches (New UI fixes & historical data loading)

**Comment by callmekatootie** [comment]
@BadalZ not yet. I intend to merge it shortly

**Comment by BadalZ** [comment]
@callmekatootie : Please merge it so we can close this issue.

**Comment by callmekatootie** [comment]
@BadalZ Shall I merge in master too? Did you get a chance to check out develop? Its live

**Comment by BadalZ** [comment]
Changes are deployed and verified hence closing the issue based on observations.
