### ISSUE TITLE
Display messages in order

### ISSUE THREAD

**Issue by BadalZ** [topcoder-platform/Lauscher#10]
Messages should be displayed on timestamp basis - Latest message on top.

**Comment by callmekatootie** [comment]
@BadalZ This is now fixed. The latest messages will now be shown first. New messages that will arrive will be shown at the top of the table.

I have pushed to `develop` and I checked just now that its working fine. Can you test and let me know if its fine and we can close this ticket?

**Comment by callmekatootie** [comment]
@BadalZ Closing this ticket. Haven't heard back so I assume all is well now.
